"""Customer profile

Revision ID: 0c5bbe771ff8
Revises: 3422a7198cbb
Create Date: 2026-06-21 03:46:06.169149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5bbe771ff8'
down_revision: Union[str, Sequence[str], None] = '3422a7198cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'external_id', name='uq_customer_external_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_customer_id', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_customer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_customer_id'))
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customers_external_id'))

    op.drop_table('customers')
    # ### end Alembic commands ###
