"""add_inbox_models

Revision ID: 4b467b252812
Revises: a73016085bc9
Create Date: 2026-07-07 07:02:44.916890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b467b252812'
down_revision: Union[str, Sequence[str], None] = 'a73016085bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS conversation_tags")
    op.execute("DROP TABLE IF EXISTS handoff_assignments")
    op.create_table('conversation_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('tag_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'tag_name', name='uq_conversation_tag')
    )
    with op.batch_alter_table('conversation_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_tags_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_tags_tag_name'), ['tag_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_tags_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('handoff_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoff_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handoff_assignments_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoff_assignments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoff_assignments_user_id'), ['user_id'], unique=False)

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_conversations")
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('handoff_status', sa.String(length=40), nullable=False, server_default='ai_handling'))
        batch_op.add_column(sa.Column('assigned_user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_assigned_user_id_users', 'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_assigned_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_assigned_user_id'))
        batch_op.drop_column('assigned_user_id')
        batch_op.drop_column('handoff_status')
        batch_op.drop_column('sla_due_at')
        batch_op.drop_column('priority')

    with op.batch_alter_table('handoff_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handoff_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_handoff_assignments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_handoff_assignments_conversation_id'))

    op.drop_table('handoff_assignments')
    with op.batch_alter_table('conversation_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_tags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_tags_tag_name'))
        batch_op.drop_index(batch_op.f('ix_conversation_tags_conversation_id'))

    op.drop_table('conversation_tags')
    # ### end Alembic commands ###
