"""add_telegram_bot_token_to_agents

Revision ID: 5a4b1bc4c8af
Revises: 0c5bbe771ff8
Create Date: 2026-06-21 05:20:34.526715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4b1bc4c8af'
down_revision: Union[str, Sequence[str], None] = '0c5bbe771ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_bot_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('telegram_bot_token')

    # ### end Alembic commands ###
