"""agent_pathways

Revision ID: 9ad0e7d48a0a
Revises: b2bc95c2745b
Create Date: 2026-06-21 21:55:35.276129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad0e7d48a0a'
down_revision: Union[str, Sequence[str], None] = 'b2bc95c2745b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathway_nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pathway_edges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('pathway_edges')
        batch_op.drop_column('pathway_nodes')

    # ### end Alembic commands ###
