"""Add Outbound Campaign and Analytics models

Revision ID: a73016085bc9
Revises: 7d9e0f12a345
Create Date: 2026-07-07 06:50:49.075952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73016085bc9'
down_revision: Union[str, Sequence[str], None] = '7d9e0f12a345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_agents',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('conversations_count', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'agent_id', 'report_date')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_companies_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_companies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_pipelines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('campaign_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_leads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_leads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_stages_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_stages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_leads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline_id', sa.String(length=36), nullable=True),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('expected_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['crm_stages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_notes_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_tasks_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_lead_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_deal_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_assignee_user_id'))

    op.drop_table('crm_tasks')
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_lead_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_deal_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_author_user_id'))

    op.drop_table('crm_notes')
    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_stage_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_lead_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_company_id'))

    op.drop_table('crm_deals')
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_leads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_name'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_email'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_customer_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_company_id'))

    op.drop_table('crm_leads')
    with op.batch_alter_table('crm_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_stages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_stages_pipeline_id'))

    op.drop_table('crm_stages')
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_leads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_leads_campaign_id'))

    op.drop_table('campaign_leads')
    with op.batch_alter_table('crm_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_sources_tenant_id'))

    op.drop_table('crm_sources')
    with op.batch_alter_table('crm_pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_pipelines_tenant_id'))

    op.drop_table('crm_pipelines')
    with op.batch_alter_table('crm_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_companies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_companies_phone'))
        batch_op.drop_index(batch_op.f('ix_crm_companies_name'))

    op.drop_table('crm_companies')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_tenant_id'))

    op.drop_table('campaigns')
    op.drop_table('analytics_agents')
    # ### end Alembic commands ###
