"""order_draft_checkout_info

Revision ID: b2bc95c2745b
Revises: 8c1655dc0a51
Create Date: 2026-06-21 05:53:38.245739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bc95c2745b'
down_revision: Union[str, Sequence[str], None] = '8c1655dc0a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=500), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_external_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('product_external_id')

    with op.batch_alter_table('order_drafts', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###
