"""add_internal_note_model

Revision ID: bf853ac3a600
Revises: 4b467b252812
Create Date: 2026-07-07 07:07:10.221879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf853ac3a600'
down_revision: Union[str, Sequence[str], None] = '4b467b252812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internal_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internal_notes_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_notes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_internal_notes_conversation_id'))

    op.drop_table('internal_notes')
    # ### end Alembic commands ###
