from uuid import NAMESPACE_URL, UUID, uuid5

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, Field

from app.api.v1.dependencies import find_tenant_for_agent
from app.limiter import limiter
from app.orchestrator import AgentOrchestrator
from app.settings import Settings, get_settings
from app.store_factory import AppStore, get_app_store

router = APIRouter(prefix="/widget", tags=["widget"])


class WidgetChatRequest(BaseModel):
    session_id: str = Field(
        ...,
        min_length=8,
        max_length=128,
        pattern=r"^[A-Za-z0-9._:-]+$",
        description="A stable anonymous session identifier generated by the widget.",
    )
    message: str = Field(..., min_length=1, max_length=4000, description="User message text.")
    customer_name: str | None = Field(None, max_length=128, description="Optional customer name")
    customer_phone: str | None = Field(None, max_length=32, description="Optional customer phone")


class WidgetChatResponse(BaseModel):
    conversation_id: UUID
    response: str
    status: str = "ok"
    confidence: float | None = None


@router.post("/chat/{agent_id}", response_model=WidgetChatResponse)
@limiter.limit("30/minute")
async def widget_chat(
    request: Request,
    agent_id: str,
    payload: WidgetChatRequest,
    settings: Settings = Depends(get_settings),
    app_store: AppStore = Depends(get_app_store),
) -> WidgetChatResponse:
    tenant_id_str = find_tenant_for_agent(agent_id, app_store)
    if not tenant_id_str:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    tenant_uuid = UUID(tenant_id_str)

    from app.api.v1.dependencies import check_billing_limit
    from app.channels import ChannelType, MessageEvent

    check_billing_limit(tenant_uuid, app_store)
    agent_uuid = UUID(agent_id)

    # Normalize incoming message to MessageEvent structure
    event = MessageEvent(
        channel=ChannelType.web_widget,
        external_chat_id=payload.session_id,
        sender_name=payload.customer_name or "Widget User",
        text=payload.message,
        raw_payload=payload.model_dump(),
    )

    # Use normalized session_id to map to a stable conversation UUID
    conversation_uuid = uuid5(NAMESPACE_URL, f"widget_session:{event.external_chat_id}:{agent_id}")

    # Resolve or create customer
    customer = app_store.get_customer_by_external_id(
        tenant_id=tenant_uuid,
        channel="web_widget",
        external_id=event.external_chat_id,
    )
    if not customer:
        customer = app_store.create_customer(
            tenant_id=tenant_uuid,
            channel="web_widget",
            external_id=event.external_chat_id,
            name=event.sender_name,
            phone=payload.customer_phone,
        )
    elif event.sender_name or payload.customer_phone:
        # Update existing customer if name or phone provided
        updates_needed = False
        if event.sender_name and customer.name != event.sender_name:
            updates_needed = True
        if payload.customer_phone and customer.phone != payload.customer_phone:
            updates_needed = True
            
        if updates_needed:
            updated = app_store.update_customer(
                tenant_id=tenant_uuid,
                customer_id=customer.id,
                name=event.sender_name or customer.name,
                phone=payload.customer_phone or customer.phone,
                tags=customer.tags,
            )
            if updated:
                customer = updated

    # Process message via Orchestrator
    orchestrator = AgentOrchestrator(store=app_store, settings=settings)

    orchestrator_result = await orchestrator.process_message(
        tenant_id=tenant_uuid,
        agent_id=agent_uuid,
        conversation_id=conversation_uuid,
        customer_message=event.text,
        channel="web_widget",
    )
    response_text = orchestrator_result.response_text

    recorded = app_store.record_chat_turn(
        tenant_id=tenant_uuid,
        agent_id=agent_uuid,
        conversation_id=conversation_uuid,
        channel="web_widget",
        customer_text=event.text,
        agent_response_text=response_text,
        customer_id=customer.id,
        confidence_score=orchestrator_result.confidence_score,
    )
    if not recorded:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    return WidgetChatResponse(
        conversation_id=conversation_uuid,
        response=response_text,
        confidence=orchestrator_result.confidence_score,
    )

