from uuid import NAMESPACE_URL, UUID, uuid5

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, Field

from app.limiter import limiter
from app.orchestrator import AgentOrchestrator
from app.settings import Settings, get_settings
from app.store_factory import AppStore, get_app_store

router = APIRouter(prefix="/widget", tags=["widget"])


class WidgetChatRequest(BaseModel):
    session_id: str = Field(
        ...,
        min_length=8,
        max_length=128,
        pattern=r"^[A-Za-z0-9._:-]+$",
        description="A stable anonymous session identifier generated by the widget.",
    )
    message: str = Field(..., min_length=1, max_length=4000, description="User message text.")


class WidgetChatResponse(BaseModel):
    conversation_id: UUID
    response: str
    status: str = "ok"


@router.post("/chat/{agent_id}", response_model=WidgetChatResponse)
@limiter.limit("30/minute")
async def widget_chat(
    request: Request,
    agent_id: str,
    payload: WidgetChatRequest,
    settings: Settings = Depends(get_settings),
    app_store: AppStore = Depends(get_app_store),
) -> WidgetChatResponse:
    tenant_id_str = await _find_tenant_for_agent(agent_id, app_store)
    if not tenant_id_str:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    tenant_uuid = UUID(tenant_id_str)

    from app.api.v1.dependencies import check_billing_limit
    check_billing_limit(tenant_uuid, app_store)
    agent_uuid = UUID(agent_id)

    # Use session_id to map to a stable conversation UUID
    conversation_uuid = uuid5(NAMESPACE_URL, f"widget_session:{payload.session_id}:{agent_id}")

    # Process message via Orchestrator
    orchestrator = AgentOrchestrator(store=app_store, settings=settings)

    response_text = await orchestrator.process_message(
        tenant_id=tenant_uuid,
        agent_id=agent_uuid,
        conversation_id=conversation_uuid,
        customer_message=payload.message,
        channel="web_widget",
    )

    recorded = app_store.record_chat_turn(
        tenant_id=tenant_uuid,
        agent_id=agent_uuid,
        conversation_id=conversation_uuid,
        channel="web_widget",
        customer_text=payload.message,
        agent_response_text=response_text,
    )
    if not recorded:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")

    return WidgetChatResponse(conversation_id=conversation_uuid, response=response_text)


async def _find_tenant_for_agent(agent_id: str, app_store: AppStore) -> str | None:
    """
    Find the tenant that owns a given agent.
    Iterates through all tenants to find the agent.
    """
    try:
        agent_uuid = UUID(agent_id)
    except ValueError:
        return None

    if hasattr(app_store, "agents"):
        agent = app_store.agents.get(agent_uuid)
        if agent:
            return str(agent.tenant_id)

    from app.settings import get_settings

    settings = get_settings()
    agent = app_store.get_agent(UUID(settings.demo_tenant_id), agent_uuid)
    if agent:
        return settings.demo_tenant_id

    return None
