import os
from app.settings import get_settings
from app.api.v1.health import _llm_readiness, _provider_readiness
from datetime import UTC, datetime

def generate_readiness_report():
    settings = get_settings()
    
    providers = [
        _llm_readiness(settings),
        _provider_readiness(
            provider="telegram",
            configured=bool(settings.telegram_bot_token),
            detail="TELEGRAM_BOT_TOKEN",
        ),
        _provider_readiness(
            provider="yookassa",
            configured=bool(settings.yookassa_shop_id and settings.yookassa_secret_key),
            detail="YOOKASSA_SHOP_ID + YOOKASSA_SECRET_KEY",
        ),
        _provider_readiness(
            provider="iiko",
            configured=bool(settings.iiko_api_login and settings.iiko_api_password),
            detail="IIKO_API_LOGIN + IIKO_API_PASSWORD",
        ),
        _provider_readiness(
            provider="twilio_voice",
            configured=bool(
                settings.twilio_account_sid
                and settings.twilio_auth_token
                and settings.twilio_phone_number
            ),
            detail="TWILIO_ACCOUNT_SID + TWILIO_AUTH_TOKEN + TWILIO_PHONE_NUMBER",
        ),
        _provider_readiness(
            provider="speech_stt_tts",
            configured=bool(settings.openai_api_key or settings.yandex_api_key or settings.deepgram_api_key),
            detail="YANDEX_API_KEY, DEEPGRAM_API_KEY or OPENAI_API_KEY",
        ),
        _provider_readiness(
            provider="asterisk_ari",
            configured=bool(settings.asterisk_ari_username and settings.asterisk_ari_password),
            detail="ASTERISK_ARI_USERNAME + ASTERISK_ARI_PASSWORD",
        ),
    ]
    
    if any(p.status == "missing_secret" for p in providers):
        status = "degraded"
    elif any(p.status == "local_stub" for p in providers):
        status = "mock_only"
    else:
        status = "ready"
        
    report = [
        "# Production Readiness Report v1",
        f"**Status**: {status.upper()}",
        f"**Environment**: {settings.app_env}",
        f"**Store Backend**: {settings.store_backend} (RLS Enabled: {settings.store_backend == 'sqlalchemy'})",
        f"**Checked At**: {datetime.now(UTC)}",
        "",
        "## Providers Status",
        ""
    ]
    
    for provider in providers:
        icon = "✅" if provider.status == "configured" else ("⚠️" if provider.status == "local_stub" else "❌")
        report.append(f"### {icon} {provider.provider.title()}")
        report.append(f"- **Status**: {provider.status}")
        report.append(f"- **Detail**: {provider.detail}")
        report.append("")
        
    report.append("---")
    report.append("*Generated by `generate_readiness_report.py`*")
    
    report_content = "\n".join(report)
    
    # Write to project root
    file_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "READINESS.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    print(f"Readiness report generated at {file_path}")

if __name__ == "__main__":
    generate_readiness_report()
