"""Initial migration

Revision ID: b7917ceca4f4
Revises:
Create Date: 2026-06-19 23:00:48.701297

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b7917ceca4f4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
